
KEYBOARD = overwatch

KEYMAP = default

DIODES = COL2ROW

BOOTMAGIC_ENABLE = yes
NKRO_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAS_KEY_ENABLE = no

BOOTLOADER = caterina

DEBUG_ENABLE = no
CONSOLE_ENABLE = no

MOUSEKEY_ENABLE = no
SLOW_FLASH = no
PIN_COMPATIBLE = promicro